[package]
name = "tiny-physics-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14", optional = true }

[features]
default = ["visualize"]
visualize = ["dep:macroquad"]
